from pathlib import Path
from bs4 import BeautifulSoup
import json,hashlib,subprocess,re,ast,datetime
p=Path(__file__).resolve().parent;repo=p.parents[4]; rel=lambda f:str(Path(f).resolve().relative_to(repo)); sha=lambda b:hashlib.sha256(b).hexdigest()
def proof(f):
 f=Path(f); b=f.read_bytes();return dict(file=rel(f),bytes=len(b),sha256=sha(b))
manifest=repo/'references/proceedings/ASPLOS/2025/manifest.json';m={r['program_order']:r for r in json.loads(manifest.read_text())['papers']}
sources=sum([json.loads(f.read_text()) for f in sorted(p.glob('download*.json.results.json'))],[])
for s in sources:s['file']=rel(s['file']);s['id']='asplos25-followup-'+s['id']
meta={151:('pruner-v3-abstract','pruner-v3',[4,5,6,7,8],[1,5,6]),152:('relax-arxiv','relax-author',[5,9,10,11],[1,9]),182:('vattention-abstract','vattention',[5,6,7,8,9,13,14],[1,6,13])}
notes={151:['Explicit arXiv v3 selected; earlier speculative-title version differs in title/authors. DOI and all 13 authors verified on PDF p1.','The paper reports tuning/search-time results separately from resulting program latency. p9–17 full evaluation/reference text not read.','READINGS.md proposed LLM-agent experiment is editorial extension, not a claimed Pruner implementation feature.'],152:['Canonical full abstract is arXiv v2 HTML; representative PDF is the author-hosted formal 16-page paper. Abstract wording differs slightly; preserve both.','HTML lists Steven S. Lyubomirsky and Jared G. Roesch; formal PDF/manifest omit the middle initials. Exact DOI and other authors match.','Only selected Python pass wrapper/docstring definitions at pinned TVM commit read; not the corresponding C++ transformations/default pipeline/tests.'],182:['arXiv v3 PDF prints Ramchandran Ramjee; HTML/manifest use Ramachandran Ramjee. Exact DOI/title and other authors match.','This is vAttention virtual-memory management (2405.04437), not the unrelated verified sparse attention paper (2510.05688).','p10–12 complete performance/ablation results not read; abstract 1.23x not independently performance-validated.','Paper p9 and pinned repository README differ in common serving framework and FlashInfer versions; preserve both environments and do not infer upstream feature parity.']}
rec=[]
for n,(html,pdf,pages,views) in meta.items():
 s=BeautifulSoup((p/(html+'.html')).read_bytes(),'html.parser');e=s.select_one('blockquote.abstract');e.select_one('.descriptor').extract();abstract=e.get_text(' ',strip=True);af=p/f'{n}-abstract.txt';af.write_text(abstract+'\n');x=m[n];authors=[a['content'] for a in s.find_all('meta',attrs={'name':'citation_author'})];title=s.find('meta',attrs={'name':'citation_title'})['content'];pf=p/(pdf+'.pdf');count=int(re.search(r'^Pages:\s+(\d+)',subprocess.check_output(['pdfinfo',str(pf)],text=True),re.M).group(1))
 d={'program_order':n,'doi':x['doi'],'title':title,'authors':authors,'source_file':rel(p/(html+'.html')),'source_sha256':sha((p/(html+'.html')).read_bytes()),'extraction':'HTML blockquote.abstract; remove .descriptor; BeautifulSoup get_text(" ", strip=True).','history':s.select_one('div.submission-history').get_text(' ',strip=True),'abstract':abstract,'abstract_sha256':sha(abstract.encode()),'abstract_text_file':proof(af),'reading_status':'full_abstract_and_selected_sections_read','read_date':'2026-09-09','identity':{'official_program_doi':x['doi'],'publisher_title':x['title'],'publisher_author_names':[' '.join([a.get('given',''),a['family']]).strip() for a in x['author_metadata']],'pdf_title_doi_visually_verified':True,'author_variants_explicitly_recorded':True},'representative_pdf':dict(**proof(pf),pages=count,text=proof(pf.with_suffix('.txt')),layout_text=proof(pf.with_suffix('.layout.txt')),first_page_text=proof(pf.with_suffix('.first.txt'))),'selected_reading':{'physical_pdf_pages':pages,'scope':'Complete text on these selected physical pages read; other body pages not claimed. First physical page read separately for complete abstract/title/authors/DOI. No program/model/driver execution or benchmark reproduction.','page_text':{str(i):proof(p/f'{pdf}.p{i:02}.txt') for i in pages},'viewed_page_images':{str(i):dict(**proof(p/(pdf+'.p1.png' if i==1 else f'{pdf}.p{i:02}.png')),actually_viewed=True) for i in views}},'version_notes':notes[n],'editorial_notes':rel(p/'READINGS.md')}
 rec.append(d)
software=[]
for n,name,metadata,filename in [(151,'qiaolian9/Pruner','pruner-github-master','pruner-source'),(152,'apache/tvm','tvm-github','tvm-source'),(182,'microsoft/vattention','vattention-github','vattention-source')]:
 d=json.loads((p/(metadata+'.html')).read_text()); scope='Complete pinned README read, including dependencies, integration, benchmark description and caveats.'
 extra={}
 if n==152:
  scope='Only definitions/docstrings/wrapper bodies StaticPlanBlockMemory, FuseTIR, RewriteCUDAGraph, AllocateWorkspace statically read; AST parsed as data, downloaded module not imported/executed.';t=(p/(filename+'.html')).read_text();tree=ast.parse(t);extra['selected_source_lines']={node.name:[node.lineno,node.end_lineno] for node in tree.body if isinstance(node,ast.FunctionDef) and node.name in ['StaticPlanBlockMemory','FuseTIR','RewriteCUDAGraph','AllocateWorkspace']}
 software.append(dict(program_order=n,repository=name,commit=d['sha'],commit_date=d['commit']['committer']['date'],commit_metadata=proof(p/(metadata+'.html')),source=proof(p/(filename+'.html')),reading_scope=scope,**extra))
calc={'label':'Editorial calculations from stated paper parameters, not benchmark reproduction','pruner':{'source':'p4 Table1, Orin ResNet50 2000 trials','exploration_minutes':35,'training_minutes':5.4,'measurement_minutes':44.4,'total_minutes':84.8,'exploration_share':35/84.8,'speedup_if_exploration_zero_other_costs_unchanged':84.8/49.8},'relax':{'source':'p5 Figure4 FP32 X[n,128] W[128,256] -> [n,256]','flops_coefficient_n':2*128*256,'logical_bytes_constant_weights':4*128*256,'logical_bytes_coefficient_n':4*(128+256),'unfused_relu_extra_logical_bytes_coefficient_n':2*4*256,'workspace_example_bytes':8*1024*1024*4,'caveat':'Logical once-read/write byte model; not measured HBM traffic. Weight caching and repeated tiling transfers can change traffic.'},'vattention':{'source':'p6/p9 Yi34B TP2 FP16 N60 Hkv4 D128 per worker','kv_bytes_per_token_per_worker':2*60*4*128*2,'kv_bytes_32k_per_request_per_worker':2*60*4*128*2*32768,'kv_bytes_32k_batch16_per_worker':2*60*4*128*2*32768*16,'approx_weight_bytes_per_worker':34e9*2/2,'approx_weights_plus_kv_gib':(34e9+2*60*4*128*2*32768*16)/(1024**3),'map_latency_example_ms':120*40/1000,'internal_fragmentation_upper_bound_per_request_2mib_bytes':120*2*1024*1024,'internal_fragmentation_upper_bound_per_request_64kib_bytes':120*64*1024,'caveat':'34B rounded parameter estimate; exact checkpoint config needed for deployment. KV capacity/allocation rate/attention read traffic are different quantities.'}}
(p/'calculations.json').write_text(json.dumps(calc,ensure_ascii=False,indent=2)+'\n')
bundle={'scope':'Independent followup for three previously missing primary abstracts plus selected body scopes. Only this new directory was written. No shared-index/outline/verifier/Git mutation.','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'selection':proof(p/'selection.json'),'sources':sources,'records':rec,'software_sources':software,'new_full_abstracts':3,'representative_pdfs':3,'representative_pdf_pages':sum(r['representative_pdf']['pages'] for r in rec),'selected_body_reading_records':3,'selected_body_physical_pages':sum(len(r['selected_reading']['physical_pdf_pages']) for r in rec),'abstract_identity_pages_read_separately':3,'actual_rendered_pages_viewed':8,'body_reading_is_full_paper':False,'calculations':proof(p/'calculations.json'),'notes':proof(p/'READINGS.md'),'unresolved':['No reproduction of paper headline performance; unselected full-result/ablation pages remain unread.','No current production-system compatibility testing, driver installation, model execution, or dynamic profiling.','Root must deduplicate against fresh reading coverage before integrating; counters here are this package scope only.']}
(p/'reading-records.json').write_text(json.dumps(bundle,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in bundle.items() if isinstance(v,(int,bool))}))
