"""Build bounded PIM/serverless abstract packet only."""
from pathlib import Path
import json,hashlib,re,datetime,subprocess
from bs4 import BeautifulSoup
P=Path(__file__).resolve().parent;ROOT=P.parents[4]
def sha(b):return hashlib.sha256(b).hexdigest()
def proof(f):
 f=Path(f);b=f.read_bytes();return {'file':str(f.relative_to(ROOT)),'bytes':len(b),'sha256':sha(b)}
def dump(name,x):(P/name).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
M={r['program_order']:r for r in json.loads((ROOT/'references/proceedings/ASPLOS/2025/manifest.json').read_text())['papers']}
sources=[]
for f in sorted(P.glob('sources-*.json.results.json')):
 for r in json.loads(f.read_text()):r['file']=str(Path(r['file']).relative_to(ROOT));sources.append(r)
config={154:('154-arxiv-paper','html','2502.15470v2'),156:('156-institution-paper','pdf','author/institution ASPLOS 2024 volume 4 layout, presented in 2025'),158:('158-arxiv-paper','html','2502.17006v1'),170:('170-author-paper','pdf','author publication-layout PDF'),171:('171-arxiv-paper','html','2503.05130v1'),172:('172-author-paper','pdf','author publication-layout PDF')}
decisions={154:('medium','候选：动态并行参数会改变算子算术强度，固定 GPU/PIM 映射可能失效；需正文核在线判断成本和平台。'),156:('medium','候选：分层编译抽象统一近存／存内目标；需正文核通用表示与设备专用成本边界。'),158:('medium','候选：计算／存储模式选择加入跨算子资源取舍；需正文核切换成本与硬件评测条件。'),170:('conditional','条件候选：暖容器等待与冷启动、保活驱逐的取舍；原工作是 FaaS，尚不能泛化为 Agent 结果。'),171:('high','高优先正文候选：纵向资源份额与横向实例数联动；需核 QoS、碎片定义和伸缩成本。'),172:('high','高优先正文候选：CUDA Graph 和 KV 初始化状态物化降低冷启动；需核恢复限制、框架版本与 TTFT 指标。')}
records=[]
for n,(stem,kind,version) in config.items():
 m=M[n];authors=[' '.join([a.get('given',''),a.get('family','')]).strip() for a in m['author_metadata']]
 extra={};history=None
 if kind=='html':
  src=P/f'{n}-arxiv.html';s=BeautifulSoup(src.read_bytes(),'html.parser');a=s.select_one('blockquote.abstract');a.select_one('.descriptor').decompose();abstract=a.get_text(' ',strip=True);history=s.select_one('.submission-history').get_text(' ',strip=True)
  extraction={'kind':'arxiv_html','selector':'blockquote.abstract','remove_selector':'.descriptor','normalization':'BeautifulSoup get_text(" ",strip=True); preserve original LaTeX/spelling/punctuation.'};sourceurl='https://arxiv.org/abs/'+version
 else:
  src=P/(stem+'.pdf');first=(P/(stem+'.first.txt')).read_text();text=first.split('Abstract',1)[1]
  end='Keywords:' if n==156 else 'CCS Concepts:' if n==170 else 'TTFT) by 53.0%.'
  abstract=' '.join((text[:text.index(end)+(len(end) if n==172 else 0)]).split());extraction={'kind':'pdf_first_page','command':'pdftotext -f 1 -l 1 input.pdf -','start_after':'Abstract','end_marker':end,'include_end_marker':n==172,'normalization':'Collapse whitespace only; no -raw, manual content repair or footer removal.'}
  sourceurl=next(x['url'] for x in sources if x['id']==stem)
 af=P/f'{n}-abstract.txt';af.write_text(abstract+'\n');pdf=P/(stem+'.pdf');pages=int(subprocess.check_output(['pdfinfo',str(pdf)],text=True).split('Pages:')[1].splitlines()[0])
 notes={154:['arXiv v2 dated 2025-02-27, 13 pages; formal manifest page range denotes 17 pages. PDF p1 has no formal DOI. Exact title and all nine authors match official/publisher manifest; no claim of identical version-of-record text.','Institution published PDF and fresh Crossref requests returned HTTP 429; retained without retry; Crossref body actually zero bytes.'],156:['Institution PDF p1 says ASPLOS 2024 Volume 4; official programme presentation year is 2025. Both identities retained.','Full official author Karl Friedrich Alexander Friebel appears as Karl F. A. Friebel on PDF/arXiv. Explicit identity alias only.','arXiv v4 dated 2024-05-24 is archived as version-history reference; canonical abstract extracted from institution PDF, not mixed with preprint wording.'],158:['arXiv v1 dated 2025-02-24, 16 pages; PDF p1 has no official DOI. New publisher Crossref record verifies exact title/all seven authors/formal DOI.','Abstract crosses both p1 columns; full original HTML block used instead of manually stitching PDF fragments.'],170:['Author 15-page PDF carries exact title, five authors and DOI on p1. Abstract only; general FaaS study, no AI workload evaluation claim.'],171:['arXiv v1 dated 2025-03-07, 15 pages; all seven authors and official DOI visible on p1. Abstract metrics for fragmentation, throughput and QoS retained as separate measures.'],172:['Author 16-page PDF carries exact title, five authors and DOI on p1. Abstract boundary ends before right-column timeline figure.','Cold-start materialization Medusa; do not confuse with speculative-decoding work sharing the name. KV initialization information is not asserted to mean persisted per-request token KV content.']}[n]
 identity={'official_program_doi':m['doi'],'publisher_title':m['publisher_title'],'publisher_author_names':authors,'program_order':n,'presentation_year':m['presentation_year'],'formal_page_range':m['page'],'volume_doi':m['volume_doi'],'pdf_title_authors_visually_verified':True,'pdf_official_doi_visually_verified':n in [156,170,171,172],'author_aliases':{'Karl Friedrich Alexander Friebel':'Karl F. A. Friebel'} if n==156 else {}}
 if n==158:identity['publisher_identity_source']=proof(P/'158-crossref.html')
 if n==154:identity['doi_bridge']='Existing official-program/publisher manifest exact title and all nine authors; PDF lacks DOI. Published-PDF retrieval blocked, explicitly not claimed.'
 if n==156:
  s=BeautifulSoup((P/'156-arxiv.html').read_bytes(),'html.parser');extra['related_version_metadata']={'source':proof(P/'156-arxiv.html'),'version':'arXiv:2301.07486v4','history':s.select_one('.submission-history').get_text(' ',strip=True),'canonical_abstract_from_this_source':False}
 records.append({'program_order':n,'doi':m['doi'],'title':m['title'],'authors':authors,'source_file':str(src.relative_to(ROOT)),'source_sha256':sha(src.read_bytes()),'source_url':sourceurl,'extraction_kind':extraction['kind'],'extraction':extraction,'version':version,'history':history,'abstract':abstract,'abstract_sha256':sha(abstract.encode()),'abstract_text_file':proof(af),'reading_status':'full_abstract_read','read_date':datetime.date.today().isoformat(),'identity':identity,'representative_pdf':{**proof(pdf),'pages':pages,'text':proof(pdf.with_suffix('.txt')),'layout_text':proof(pdf.with_suffix('.layout.txt')),'first_page_text':proof(pdf.with_suffix('.first.txt')),'version_relation':'13-page arXiv preprint, not formal 17-page version' if n==154 else version},'selected_reading':{'physical_pdf_pages':[],'scope':'Complete primary abstract and p1 title/authors/identity only; no selected body page read. Full PDF text mechanically archived, not body reading.','page_text':{},'viewed_page_images':{'1':{**proof(pdf.with_suffix('.p1.png')),'actually_viewed':True}}},'version_notes':notes,'body_reading_candidate_priority':decisions[n][0],'editorial_decision':decisions[n][1],**extra})
x={'scope':'Parent-assigned six PIM/compiler/serverless abstracts; no body selection or shared index/outline/Git edits.','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'selection':proof(P/'selection-snapshot.json'),'sources':sources,'records':records,'gaps':[],'software_sources':[],'new_full_abstracts':6,'representative_pdfs':6,'representative_pdf_pages':91,'selected_body_reading_records':0,'selected_body_physical_pages':0,'abstract_identity_pages_read_separately':6,'actual_rendered_pages_viewed':6,'body_reading_is_full_paper':False,'notes':proof(P/'READINGS.md'),'handoff':proof(P/'HANDOFF.md'),'unresolved':['PAPI published 17-page PDF unavailable in this batch; archived 13-page arXiv v2 instead with exact title/authors identity match.','All body-specific evaluation conditions and current framework/source adoption remain unread/unverified.','No reproduction of benchmark results, no new code, experiment, figure or outline.']}
dump('reading-records.json',x);print('Built',len(records),'abstracts,',len(sources),'responses')
