from pathlib import Path
import json,hashlib,collections
R=Path(__file__).resolve().parents[2];O=Path(__file__).parent
sha=lambda b:hashlib.sha256(b).hexdigest();digest=lambda x:sha(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode());load=lambda p:json.loads((R/p).read_text())
original=['qwen3-8b','qwen3-32b','qwen3-30b-a3b','qwen3-235b-a22b','deepseek-r1-distill-llama-70b','deepseek-v3','deepseek-v4-flash','deepseek-v4-pro','kimi-k3','qwen3.5-397b-a17b','qwen3-vl-4b'];added=['qwen3-omni-30b-a3b-instruct','fish-audio-s2-pro','qwen-image-2512','flux2-klein-4b','minimax-h3','wan2.2-ti2v-5b'];deps=['qwen3','flash-linear-attention','fast-hadamard-transform','qwen-image-source','flux2-source','float8-format'];lock=load('configs/sources.lock.json')['sources'];selected=sorted([r for r in lock if r['model'] in original+added+deps],key=lambda r:(r['model'],r['file']));assert len({r['file'] for r in selected})==len(selected)
for r in selected:
 assert r['status']=='downloaded';b=(R/r['file']).read_bytes();assert sha(b)==r['sha256'] and len(b)==r['bytes'];assert r.get('revision') and r.get('url')
auxpaths=['configs/image-generation.lock.json','configs/vision-encoding.lock.json','research/generative-audio-analysis/sources.lock.json','research/generative-video-analysis/manifest.json'];aux=[]
for p in auxpaths:
 d=load(p);rows=d['sources'] if isinstance(d,dict) else d;out=[]
 for r in rows:
  path=R/r['file']
  if not path.is_file():path=(R/p).parent/r['file']
  b=path.read_bytes();assert sha(b)==r['sha256'] and len(b)==r['bytes'];assert r.get('revision');out.append({**r,'file':str(path.relative_to(R))})
 aux.append({'manifest_file':p,'manifest_sha256':sha((R/p).read_bytes()),'source_count':len(out),'canonical_source_subset_sha256':digest(out),'sources':out})
by=collections.defaultdict(list)
for r in selected:by[r['model']].append(r)
models=[]
auxmap={'qwen3-vl-4b':['configs/vision-encoding.lock.json'],'qwen3-omni-30b-a3b-instruct':['research/generative-audio-analysis/sources.lock.json'],'fish-audio-s2-pro':['research/generative-audio-analysis/sources.lock.json'],'qwen-image-2512':['configs/image-generation.lock.json'],'flux2-klein-4b':['configs/image-generation.lock.json'],'minimax-h3':['research/generative-video-analysis/manifest.json'],'wan2.2-ti2v-5b':['research/generative-video-analysis/manifest.json']}
for m in original+added:
 rows=by[m];assert rows;cfg=[r for r in rows if r.get('upstream_file','').endswith('config.json') or r['file'].endswith('config.json')];assert cfg,m;models.append({'model':m,'scope':'original_11' if m in original else 'user_additional_6','necessary_inputs':'accepted_fixed_config_and_model_specific_implementation_contract','root_source_count':len(rows),'root_repositories':sorted({r.get('repository','') for r in rows}),'root_revisions':sorted({r['revision'] for r in rows}),'auxiliary_manifests':auxmap.get(m,[]),'root_source_dependencies':['qwen3'] if m.startswith('qwen3-') and m in original[:4] else ['flash-linear-attention'] if m=='kimi-k3' else ['fast-hadamard-transform','float8-format'] if m.startswith('deepseek-v4') else ['qwen-image-source'] if m=='qwen-image-2512' else ['flux2-source'] if m=='flux2-klein-4b' else [],'runtime_or_complete_forward_acceptance':False})
k=load('research/f02-final-review/kimi-recheck.json');assert k['same_revision'];assert sha((R/k['file']).read_bytes())==k['sha256'];gated=[r for r in lock if r['model']=='llama3.1-70b'];assert len(gated)==1 and gated[0]['status']=='unavailable'
report={'work_package':'F02','reviewed_on':'2026-09-09','decision':'accepted_for_original_11_and_user_added_6_necessary_fixed_source_inputs','may_check_plan_item':True,'scope':'Fixed official config/model-specific implementation and auxiliary source contracts; not complete recursive installation dependency closure, full checkpoint availability or end-to-end forward support','binding':{'canonicalization':'Selected complete source-lock records sorted(model,file), UTF8 JSON ensure_ascii=False sort_keys=True separators=(comma,colon); auxiliary complete normalized rows retained separately','root_model_source_count':len(selected),'root_model_source_subset_sha256':digest(selected),'whole_source_lock_snapshot_sha256':sha((R/'configs/sources.lock.json').read_bytes()),'root_sources':selected,'auxiliary_source_manifests':aux},'models':models,'generic_70b_representative':{'selected':'deepseek-ai/DeepSeek-R1-Distill-Llama-70B','revision':by['deepseek-r1-distill-llama-70b'][0]['revision'],'identity':'DeepSeek official distilled model based on Llama70B; not Meta Llama3.1 Instruct checkpoint','original_gated_record_retained':gated[0],'no_authorization_bypass_or_identity_rewrite':True},'kimi_fixed_revision_recheck':k,'known_source_conflicts':[{'model':'kimi-k3','issue':'69 A_log checkpoint tensors128 versus implementation/config96 KDAheads','state':'fixed_version_source_discrepancy_retained; current official API revision unchanged','acceptance_effect':'Does not negate existence/provenance of necessary inputs; blocks claiming shape-complete runtime load or corrected numerical/state sizing'}],'checks':{'original_models':11,'additional_models':6,'root_sources_sha_and_bytes_pass':len(selected),'auxiliary_records_sha_and_bytes_pass':sum(a['source_count'] for a in aux),'qwen35_independent_text_shape_verification':'research/f02-qwen35-independent/verification.json','qwen35_204_timestamp_records_merged':all('downloaded_at'in r for r in by['qwen3.5-397b-a17b']),'kimi_no_header_redownload':True},'remaining_required_actions_for_this_necessary_input_scope':[],'separate_followup':['Full Qwen3.5 forward and runtime load; vision/MTP full expected shape and code paths','Resolve K3 fixed-version A_log shape contradiction before claiming runtime compatible complete checkpoint execution','Actual tokenizer/processor assets and complete dependency closure where string/media runtime execution is requested','Complete generation/VL/Omni request graphs and stage semantics under original chapter tasks','Weights are not downloaded by metadata acceptance; gated Meta model remains unavailable without separately authorized access']}
report['independent_evidence']=[{'file':f,'sha256':sha((R/f).read_bytes())} for f in ['research/f02-qwen35-independent/verification.json','research/f02-qwen35-independent/REVIEW.md','research/f02-final-review/kimi-recheck.json']]
(R/'inventory/f02-source-review.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');(O/'verification.json').write_text(json.dumps({'root_sources':len(selected),'auxiliary_sources':sum(a['source_count']for a in aux),'original':11,'added':6,'passed':True,'inventory_sha256':sha((R/'inventory/f02-source-review.json').read_bytes())},indent=2)+'\n');print('F02accepted',len(selected),'root sources',sum(a['source_count']for a in aux),'auxiliary records')
