"""Package the archived runner without changing its evaluation schedule."""
from pathlib import Path
import hashlib
import importlib.util
import json
import shutil
import sys

P=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(P/'src'))
from infra_calc.topics.kv_quality import read_records


def prepare(output):
    if output.exists():raise ValueError('Use a fresh output directory')
    data,sources=read_records()  # all archived source bytes are verified first
    root=P/'sources/kv-quality'
    spec=importlib.util.spec_from_file_location('archived_quality_runner',root/'run.py')
    runner=importlib.util.module_from_spec(spec);spec.loader.exec_module(runner)
    class NoTokenizer:
        def apply_chat_template(self,messages,**kwargs):
            assert kwargs==dict(tokenize=True,return_dict=False,add_generation_prompt=True,enable_thinking=False)
            return []
    tasks=[]
    for original in data['results/bf16/inputs.json']['tasks']:
        regenerated=runner.fixture(NoTokenizer(),original['rows'],original['seed'],original['id'])
        for key in ('id','rows','seed','messages','expected'):
            if regenerated[key]!=original[key]:raise ValueError('Task changed: '+key)
        tasks.append({key:original[key] for key in ('id','rows','seed','messages','expected')})
    output.mkdir(parents=True)
    for name in ('run.py','probe.py'):shutil.copyfile(root/name,output/name)
    (output/'expected-tasks.json').write_text(json.dumps(tasks,indent=2)+'\n')
    config=P/'configs/models/qwen3-32b/config.json'
    manifest=dict(status='prepared, not executed',target_model='qwen3-32b',target_config_sha256=hashlib.sha256(config.read_bytes()).hexdigest(),
        target_config_file=str(config.relative_to(P)),archived_runtime='vllm 0.23.0; BF16 weights and KV; TRITON_ATTN',
        distinct_tasks=len(tasks),token_ids='Must be regenerated by the target tokenizer; expected-tasks intentionally contains no token IDs',
        invocation='python run.py --model /absolute/path/to/pinned/Qwen3-32B --output /fresh/output/directory --kv-dtype auto',
        scope='Original calibration, warmups, natural/fixed interleaving and seeded randomized trial order retained byte-for-byte. Quality scoring must select formal natural rows only. No model weights or runtime downloaded by prepare.',
        files={name:hashlib.sha256((output/name).read_bytes()).hexdigest() for name in ('run.py','probe.py','expected-tasks.json')})
    (output/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    return manifest

if __name__=='__main__':
    import argparse
    parser=argparse.ArgumentParser();parser.add_argument('--output',type=Path,required=True)
    print(json.dumps(prepare(parser.parse_args().output),indent=2))
